stages:
  - build
  - deploy
  
build:
    stage: build
    image: java:8-jdk
    script:
    - cd ./Backend
    - chmod +x ./gradlew
    - ./gradlew build
    artifacts:
        paths:
            - ./Backend/build/libs/*.jar
        expire_in: 1 week
    only:
        - master

deploy:
    stage: deploy
    image: teke97/sshpass_alpine:latest
    before_script:
    - apt-get update -y && apt-get install sshpass
    script:
    - ls ./Backend/build/libs
    - sshpass -p 
    - sshpass -p $DEPLOY_PASS ssh $DEPLOY_USER@coms-309-sb-5.misc.iastate.edu sudo su;/etc/init.d/cyclone_insider stop
    - sshpass -p $DEPLOY_PASS scp ./Backend/build/libs/Cyclone_Insider.jar $DEPLOY_USER@coms-309-sb-5.misc.iastate.edu:Cyclone_Insider.jar
    - sshpass -p $DEPLOY_PASS ssh $DEPLOY_USER@coms-309-sb-5.misc.iastate.edu sudo su;/etc/init.d/cyclone_insider start