stages:
- build_backend
- deploy_backend

build_backend:
    cache:
        paths:
        - ./Backend/.gradle/wrapper
        - ./Backend/.gradle/caches
    stage: build_backend
    image: java:8-jdk
    script:
    - cd ./Backend
    - chmod +x ./gradlew
    - ./gradlew build
    artifacts:
        paths:
            - ./Backend/build/libs/*.jar
        expire_in: 1 week
    only:
        - master

deploy_backend:
    stage: deploy_backend
    image: teke97/sshpass_alpine:latest
    when: manual
    script:
    - ls ./Backend/build/libs
    - sshpass -p "${DEPLOY_PASS}" scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no ./Backend/build/libs/Cyclone_Insider.jar ${DEPLOY_USER}@coms-309-sb-5.misc.iastate.edu:Cyclone_Insider.jar
    - sshpass -p "${DEPLOY_PASS}" ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no cyclone_insider@coms-309-sb-5.misc.iastate.edu 'echo insider1234 | sudo -S systemctl restart cyclone_insider.service'